#服务端口
server:
  port: 8080

logging:
  level:
    root: info

spring:
  application:
    name: web #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.55.130.141:3306/mp3Score-sys?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: mp3Score
  redis:
    host: 114.55.130.141
    port: 6379
#    password: 'redis2020'
  servlet:
    multipart:
      maxFileSize: 201MB
      maxRequestSize: 201MB
  http:
    multipart:
      max-file-size: 201MB
      max-request-size: 201MB
    servlet:
      multipart:
        max-file-size: 201MB
        max-request-size: 201MB

# MyBatis Plus 的配置项
mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.cloud.web.dao.model
  configuration:
    map-underscore-to-camel-case: true

#eureka:
#  client:
#    service-url:
#      defaultzone: http://127.0.0.1:8761/eureka
#  instance:
#    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
#    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
