#服务端口
server:
  port: 8080

logging:
  level:
    root: info

spring:
  application:
    name: web #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bigdata?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 521775

#  redis:
#    host: 10.70.30.24
#    port: 6379
#    password: 'redis2020'
#    database: 6
#    channel: 1C1F1B01
#    batteryChannel: 1C1F1405

# MyBatis Plus 的配置项
mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.cloud.web.dao.model
  configuration:
    map-underscore-to-camel-case: true


#  redis:
#    host: 10.70.30.24
#    port: 6379
#    password: 'redis2020'
#    database: 6
#    channel: 1C1F1B01
#    batteryChannel: 1C1F1405

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8088/eureka
#  instance:
#    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
#    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
##    #表示是否将自己注册进eureka  默认为true
##    register-with-eureka: true
##    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
##    fetch-registry: true

eureka:
  client:
    service-url:
      defaultzone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
