#服务端口
server:
  port: 11011

#服务名称
spring:
  application:
    name: eureka

#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/bigdata?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: ???

#  redis:
#    host: 10.70.30.24
#    port: 6379
#    password: 'redis2020'
#    database: 6
#    channel: 1C1F1B01
#    batteryChannel: 1C1F1405

eureka:
  instance:
    hostname: 127:0.0.1
  client:
    service-url:
      defaultZone: http://localhost:11011/eureka/
    register-with-eureka: false
    fetch-registry: false